spring:
  datasource:
    url: jdbc:mysql://rdsmyam6nqwuywe.mysql.rds.aliyuncs.com:3306/dev_school_master?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: dev_admin_school
    password: XZxhUt7svO51fyg6Gg5V
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: common-test-service
server:
  port: 8079
