spring:
  activiti:
    process-definition-location-prefix: classpath*:/processes/
    check-process-definitions: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: common-test-service
  redis:
    host: 127.0.0.1
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池中的最小空闲连接
        min-idle: 0
      #连接超时时间（毫秒）
      timeout: 5000
  #liquibase:
    #enabled: true
    #change-log: "classpath:/liquibase/liquibase-master2.xml"
server:
  port: 8079
#MyBatis配置
mybatis:
  mapper-locations: classpath:com/examples/demo/cases/mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
