spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: common-test-service
server:
  port: 8079
#MyBatis配置
mybatis:
  mapper-locations: classpath:com/examples/demo/cases/mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
